### ISSUE TITLE
Could not find options.txt file. Defaulting to English.

### ISSUE THREAD

**Issue by Baalith** [WildBamaBoy/radix-core#11]
I run my MC (1.7.10 @Forge 10.13.3.1381) at a custom directory set via the setting in the standard launcher. Each time I start up mc together with several other mods I get this message in the log:

[21:16:48] [Client thread/ERROR] [RadixCore/MCA]: NullPointerException while trying to read options.txt. Defaulting to English.

The file options.txt is definitely present in my game directory which is set to
"D:\User\minecraft\client\1.7.10\sp\Forge_10.13.3.1381"

**Comment by WildBamaBoy** [comment]
This is only used to determine the language that will be used. Currently not fully implemented so this can be ignored.
