### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by RodrigoTaipe93** [WildBamaBoy/radix-core#13]
So, after I entered a village, this crash happens.

>http://pastebin.com/mM4rfKwU

>http://pastebin.com/k4LQBfqh

Modpack used > http://s2.postimg.org/ffn8o6289/Modpack_I.jpg

PC info:

MAC - OSX YOSEMITE - Version 10.10.3 -  iMac - 2.9Ghz Intel core 5 - 8 Gb 1600 Mhz DDR3 - NVIDIA GeForce GT 650 M 512Mb - 

Java version: Java 8 - 45

Forge: At moment of crash: 10.13.3.1403

Forge now: 10.13.3.1408

**Comment by WildBamaBoy** [comment]
#8, #9, #10

**Comment by WildBamaBoy** [comment]
Will update on Friday, will likely fix the issue.

**Comment by WildBamaBoy** [comment]
Updating going live in a few minutes.
