### ISSUE TITLE
"io.Netty" & "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by RodrigoTaipe93** [WildBamaBoy/radix-core#14]
There is another issue with the mod!

>http://pastebin.com/kixMz4X7

>http://pastebin.com/QEtkxUqh 

This time with something “io.netty” and Spawn mob thingy

Modpack used: http://s28.postimg.org/5n2b9jhvx/Modpack_I.jpg

PC info:

MAC - OSX YOSEMITE - Version 10.10.3 - iMac - 2.9Ghz Intel core 5 - 8 Gb 1600 Mhz DDR3 - NVIDIA GeForce GT 650 M 512Mb -

Java version: Java 8 - 45

Forge: At moment of crash: 10.13.3.1408

**Comment by WildBamaBoy** [comment]
Man, you get the strangest crashes. Does it happen on a new world or are you still attempting to use the older one?

**Comment by RodrigoTaipe93** [comment]
Using an older one. However, I saved my world previously to the crash. Before that, the world was working fine.

I used the seed: -8913466909937400889 [All biomes seed]

If it helps, there are some mods which add new villagers or modified villagers behaviour: Revamp, Chocolate Quest, Psychedelicraft, Gravestone mod, Evilcraft, Rediscovered mod, Youtubers+ and Enviromine.

Can you explain in easy terms what’s the reason of the crash?

What is your recommendation? Can I create a new world using the same seed? Is it something to do with the size of the map or maybe the RAM?

THANKS IN ADVANCED FOR YOUR RESPONSE

**Comment by WildBamaBoy** [comment]
This should no longer be an issue in later versions.
