### ISSUE TITLE
Missing sprinting "animation"

### ISSUE THREAD

**Issue by CSOmini** [WildBamaBoy/radix-core#16]
When I use RadixCore (any version for 1.8) there is no sprinting "animation". Normally, when you start to sprint, your FoV gets bigger for the time you're sprinting, but if I have RadixCore installed this won't happen. I made sure it's not a problem of MCA - it happens when I install RadixCore only.

**Comment by WildBamaBoy** [comment]
Can't reproduce this issue. Ensure no other mod is causing the problem.

**Comment by CSOmini** [comment]
NO other mod is causing this. I tested it just with this mod installed.
Am 24.08.2015 20:42 schrieb "WildBamaBoy" <notifications@github.com>:

**Comment by WildBamaBoy** [comment]
¯\_(ツ)_/¯ 
Can't reproduce with just RadixCore 2.0.4 on Forge 1450. RadixCore doesn't do anything when installed by itself, either, aside from check for updates.
