### ISSUE TITLE
log spam causing lag and log file in extreme sizes (1 GB and more) 

### ISSUE THREAD

**Issue by walkerjonny** [WildBamaBoy/radix-core#21]
My log file gets spammed with the following error messages caused by RadixCore:
http://pastebin.com/hj23CQ0R
This causes serous lag and extreme sized log files (more hundred MB up to 1 GB and more).
I'm playing with
MCA-1.7.10-5.1.1.1-universal.jar
and 
RadixCore-1.7.10-2.1.1-universal.jar

**Comment by WildBamaBoy** [comment]
Should be fixed
