### ISSUE TITLE
Crash and Cannot Open Game

### ISSUE THREAD

**Issue by trollingwampa** [WildBamaBoy/radix-core#25]
My in-game daughter died so I crafted a tombstone in her memory. My game crashed after I placed down the tombstone. Now every time I go back into that game, it crashes immediately. This is annoying and I would love it if you could fix it.

The Mods installed:
-Minecraft Coder Pack
-Forge Mod Loader
-Minecraft Forge
-LiteLoader
-CodeChicken Core
-Cyclops Core
-Dynamic Lights
-Dynamic Lights Burning Entity Module
-Dynamic Lights Creeper Module
-Dynamic Lights EntityItem Module
-Dynamic Lights Entity Light Module
-Dynamic Lights Mob Equipment Light Module
-Dynamic Lights Fiery Arrows Light Module
-Dynamic Lights Flood Light
-Dynamic Lights OtherPlayers Light Module
-Dynamic Lights Player Light Module
-EnderStorage
-EvilCraft
-Grappling hook mod
-Immersive Craft
-Just Enough Items
-Just Backpacks
-Mantle
-RadixCore
-Minecraft Comes Alive
-Parachute Mod
-Sound Filters
-Tinkers' Construct
-OptiFine HD U B6

Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CodeChickenCorePlugin (CodeChickenCore-1.9.4-2.0.4.71-universal.jar)
  CCCDeobfPlugin (unknown)
  DLFMLCorePlugin (DynamicLights-1.9.4.jar)
  CCLCorePlugin (CodeChickenLib-1.9.4-2.1.2.42-universal.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/20/16 3:40 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2713)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1747)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1334)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2713)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1747)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TrollingWampa'/277, l='MpServer', x=-1573.51, y=73.00, z=1550.23]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-256,64,212), Chunk: (at 0,4,4 in -16,13; contains blocks -256,0,208 to -241,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 799162 game time, 1014529 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 24 total; [EntityHuman['Irene'/448, l='MpServer', x=-1563.79, y=73.77, z=1557.61], EntityLeashKnot['entity.LeashKnot.name'/482, l='MpServer', x=-1507.50, y=74.50, z=1550.50], EntityPig['Pig'/290, l='MpServer', x=-1592.52, y=69.00, z=1513.25], EntityPig['Pig'/291, l='MpServer', x=-1584.75, y=70.00, z=1511.50], EntityRabbit['Rabbit'/331, l='MpServer', x=-1613.00, y=62.93, z=1505.84], EntityZombie['Zombie'/302, l='MpServer', x=-1643.50, y=45.00, z=1616.50], EntitySpider['Spider'/303, l='MpServer', x=-1595.50, y=41.00, z=1578.50], EntityCreeper['Creeper'/435, l='MpServer', x=-1554.17, y=37.00, z=1570.47], EntityPig['Pig'/308, l='MpServer', x=-1565.58, y=72.00, z=1506.52], EntityPig['Pig'/309, l='MpServer', x=-1557.50, y=72.00, z=1516.74], EntityZombie['Zombie'/438, l='MpServer', x=-1606.50, y=53.00, z=1627.50], EntityZombie['Zombie'/278, l='MpServer', x=-1573.50, y=46.00, z=1544.74], EntityPig['Pig'/310, l='MpServer', x=-1564.75, y=72.00, z=1510.19], EntityPlayerSP['TrollingWampa'/277, l='MpServer', x=-1573.51, y=73.00, z=1550.23], EntityCreeper['Creeper'/344, l='MpServer', x=-1614.50, y=48.00, z=1492.50], EntityMinecartChest['Minecart with Chest'/440, l='MpServer', x=-1553.50, y=41.06, z=1539.49], EntityMinecartChest['Minecart with Chest'/441, l='MpServer', x=-1563.50, y=45.06, z=1547.50], EntityBat['Bat'/442, l='MpServer', x=-1553.88, y=46.10, z=1542.50], EntityHuman['Frederick'/443, l='MpServer', x=-1563.86, y=73.00, z=1551.48], EntityItem['item.item.seeds'/444, l='MpServer', x=-1577.04, y=73.00, z=1552.23], EntityHorse['Horse'/445, l='MpServer', x=-1589.93, y=63.00, z=1586.03], EntityPig['Pig'/286, l='MpServer', x=-1584.28, y=70.00, z=1520.48], EntityPig['Pig'/446, l='MpServer', x=-1597.21, y=64.00, z=1589.74], EntityHuman['Hildred'/447, l='MpServer', x=-1562.09, y=73.00, z=1558.70]]
	Retry entities: 1 total; [EntityLeashKnot['entity.LeashKnot.name'/482, l='MpServer', x=-1507.50, y=74.50, z=1550.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:490)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 365002512 bytes (348 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.28 Powered by Forge 12.17.0.1976 Optifine OptiFine_1.9.4_HD_U_B6 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1976.jar) 
	UCHIJAAAA	Forge{12.17.0.1976} [Minecraft Forge] (forge-1.9.4-12.17.0.1976.jar) 
	UCHIJAAAA	CodeChickenCore{2.0.4.71} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	cyclopscore{0.7.2} [Cyclops Core] (CyclopsCore-1.9.4-0.7.2.jar) 
	UCHIJAAAA	DynamicLights{1.4.2} [Dynamic Lights] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.9.4.jar) 
	UCHIJAAAA	EnderStorage{2.0.3.62} [EnderStorage] (EnderStorage-1.9.4-2.0.3.62-universal.jar) 
	UCHIJAAAA	evilcraft{0.10.6} [EvilCraft] (EvilCraft-1.9.4-0.10.6.jar) 
	UCHIJAAAA	grapplemod{1.9.4-v7} [Grappling hook mod] (grapplemod-1.9.4-v7.jar) 
	UCHIJAAAA	immcraft{1.1.7} [Immersive Craft] (immcraft-1.9.4-1.1.7.jar) 
	UCHIJAAAA	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UCHIJAAAA	fyberbackpack{1.0.2} [Just Backpacks] (justbackpacks-mc1.9.4-1.0.2.jar) 
	UCHIJAAAA	mantle{1.9.4-0.10.3.jenkins211} [Mantle] (Mantle-1.9.4-0.10.3.jar) 
	UCHIJAAAA	RadixCore{1.9.4-2.1.2} [RadixCore] (RadixCore-1.9.4-2.1.2-universal.jar) 
	UCHIJAAAA	MCA{1.9.4-5.2.0} [Minecraft Comes Alive] (MCA-1.9.4-5.2.0-FINAL-universal.jar) 
	UCHIJAAAA	parachutemod{1.4.3} [Parachute Mod] (parachutemod-ng-1.9.4-1.4.3-403.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAA	tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct] (TConstruct-1.9.4-2.3.3.jar) 
	Loaded coremods (and transformers): 
CodeChickenCorePlugin (CodeChickenCore-1.9.4-2.0.4.71-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)
  
DLFMLCorePlugin (DynamicLights-1.9.4.jar)
  atomicstryker.dynamiclights.common.DLTransformer
CCLCorePlugin (CodeChickenLib-1.9.4-2.1.2.42-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	CodeChickenCore: ignoreInvalidMCVersion state: false
	Launched Version: 1.9.4
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: net.minecraft.client.Minecraft$15@5b43d50d
	OptiFine Version: OptiFine_1.9.4_HD_U_B6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4276
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by WildBamaBoy** [comment]
Fixed on supported MCA versions 1.7.10 and 1.10.2. The 1.9.4 version is no longer supported.
