### ISSUE TITLE
[1.3.4] Clients unable to reconnect to server if RadixCore/MCA update checker fails

### ISSUE THREAD

**Issue by ntwitch** [WildBamaBoy/radix-core#6]
Clients are unable to reconnect to the server unless the client is restarted. The clients only receive a message of "Connection Lost: A fatal error has occurred, this connection is terminated."

The UpdateChecker thread is crashing when it is unable to connect to the update server. It returns null for the version and there is no null check.

The issue stops if RadixCore and MCA are removed.

RadixCore:

> java.lang.NullPointerException
> at com.radixshock.radixcore.frontend.RDXUpdateChecker.run(RDXUpdateChecker.java:48)

MCA:

> java.lang.NullPointerException
> at mca.frontend.UpdateChecker.run(UpdateChecker.java:50)

[See troubleshooting thread](http://www.reddit.com/r/FeedTheBeastCrashes/comments/2sfwwd/cant_connect_to_my_server_after_first_disconnect/)

[Full server log](https://copy.com/euDrHStXgrK0nf3Y) including some client reconnect attempts.

**Comment by prodkid** [comment]
Can also confirm this. It also causes crashes.
http://pastebin.com/sTHacN2y
